# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.UserImage = QtWidgets.QLabel(self.centralwidget)
        self.UserImage.setText("")
        self.UserImage.setObjectName("UserImage")
        self.gridLayout.addWidget(self.UserImage, 0, 1, 1, 1)
        self.search_Button = QtWidgets.QPushButton(self.centralwidget)
        self.search_Button.setObjectName("search_Button")
        self.gridLayout.addWidget(self.search_Button, 1, 1, 1, 1)
        self.CompareImage = QtWidgets.QLabel(self.centralwidget)
        self.CompareImage.setText("")
        self.CompareImage.setObjectName("CompareImage")
        self.gridLayout.addWidget(self.CompareImage, 0, 2, 1, 1)
        self.hammingdistance_label = QtWidgets.QLabel(self.centralwidget)
        self.hammingdistance_label.setText("")
        self.hammingdistance_label.setObjectName("hammingdistance_label")
        self.gridLayout.addWidget(self.hammingdistance_label, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_interface = QtWidgets.QAction(MainWindow)
        self.action_interface.setObjectName("action_interface")
        self.menu.addAction(self.action_interface)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_Button.setText(_translate("MainWindow", "查詢"))
        self.menu.setTitle(_translate("MainWindow", "設定"))
        self.action_interface.setText(_translate("MainWindow", "開啟檔案"))
